# First remove *all* keybindings
# unbind-key -a

# ─── Session & Client ───────────────────────────────────────────────────────────

bind ^X lock-server
bind ^D detach
bind * list-clients
bind S choose-session

# ─── Windows ────────────────────────────────────────────────────────────────────

bind ^C new-window -c "#{pane_current_path}"
bind H previous-window
bind L next-window
bind ^A last-window
bind ^W list-windows
bind w list-windows
bind r command-prompt "rename-window %%"
bind '"' choose-window

# ─── Panes ──────────────────────────────────────────────────────────────────────

bind s split-window -v -c "#{pane_current_path}"
bind v split-window -h -c "#{pane_current_path}"
bind | split-window
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind z resize-pane -Z
bind x swap-pane -D
bind c kill-pane
bind P set pane-border-status
bind * setw synchronize-panes

# ─── Pane Resizing ──────────────────────────────────────────────────────────────

bind -r -T prefix , resize-pane -L 20
bind -r -T prefix . resize-pane -R 20
bind -r -T prefix - resize-pane -D 7
bind -r -T prefix = resize-pane -U 7

# ─── Copy Mode ──────────────────────────────────────────────────────────────────

bind-key -T copy-mode-vi v send-keys -X begin-selection

# ─── Misc ───────────────────────────────────────────────────────────────────────

bind ^L refresh-client
bind l refresh-client
bind : command-prompt
bind K send-keys "clear"\; send-keys "Enter"
bind R source-file ~/.config/tmux/tmux.conf
